{
 "title": "dnsdist dashboard",
 "description": "Grafana Dashboard for dnsdist by PowerDNS\n\ndnsdist is a powerful DNS LoadBalancer, applicable for large-scale environments\n\nPrometheus dnsdist by PowerDNS exporter metrics.",
 "tags": [
  "prometheus",
  "powerdns"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(dnsdist_uptime, instance)"
   },
   {
    "name": "address",
    "label": "address",
    "query": "label_values(dnsdist_server_drops,address)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "dnsdist_uptime{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dnsdist_frontend_queries{frontend=\"0.0.0.0:53\",instance=~\"$instance\",proto=\"udp\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active downstreams",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dnsdist_pool_active_servers{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# of queries not answered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "round(rate(dnsdist_server_drops{address=~\"$address\"}[5m]) * 100) ",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dnsdist_server_latency{address=~\"$address\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Send Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dnsdist_downstream_send_errors{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dnsdist_downstream_timeouts{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dnsdist_frontend_queries{frontend=\"0.0.0.0:53\",instance=~\"$instance\",proto=\"tcp\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of responses received from backends",
   "type": "graph",
   "description": "Number of responses received from backends",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dnsdist_responses{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of queries answered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(dnsdist_latency0_1{instance=~\"$instance\"}[5m]))",
     "legendFormat": "0-1 ms"
    },
    {
     "expr": "sum (rate(dnsdist_latency1_10{instance=~\"$instance\"}[5m]))",
     "legendFormat": "1-10 ms"
    },
    {
     "expr": "sum (rate(dnsdist_latency10_100{instance=~\"$instance\"}[5m]))",
     "legendFormat": "10-100 ms"
    },
    {
     "expr": "sum (rate(dnsdist_latency100_1000{instance=~\"$instance\"}[5m]))",
     "legendFormat": "100-1000 ms"
    },
    {
     "expr": "sum (rate(dnsdist_latency_slow{instance=~\"$instance\"}[5m]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "response latency of the last 1K packets",
   "type": "graph",
   "description": "response latency of the last 1K packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dnsdist_latency_avg1000{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dnsdist_real_memory_usage{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{$instance}"
    }
   ]
  },
  {
   "title": "CPU msec $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dnsdist_cpu_sys_msec{instance=~\"$instance\"}[5m]))",
     "legendFormat": "System mode"
    },
    {
     "expr": "sum(rate(dnsdist_cpu_user_msec{instance=~\"$instance\"}[5m]))",
     "legendFormat": "User mode"
    }
   ]
  }
 ]
}