package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"strings"
)

// smartDistProfilePath adalah lokasi file profil SmartDist di node (dibaca
// plugin Lua). Variabel paket agar test bisa mengarahkannya ke t.TempDir().
var smartDistProfilePath = "/etc/dnsdist/smartdist-profile.lua"

// smartDistDisabledLua adalah isi file saat node tidak punya profil.
const smartDistDisabledLua = "-- SmartDist profile (auto-generated by panel agent, do not edit)\nSMARTDIST_ENABLED = false\n"

// syncSmartDistProfile menyelaraskan file profil Lua lokal dengan profil yang
// ditunjuk master lewat heartbeat. Semua error dicatat di sini.
//
// Kontrak (2026-10-09):
//   - profileID kosong        -> tulis SMARTDIST_ENABLED=false, hash "".
//   - wantHash == hash tersimpan -> tidak fetch, tidak tulis.
//   - hash beda               -> GET profil, verifikasi sha256(body)==wantHash,
//     konversi ke Lua, tulis atomik mode 0644, simpan hash.
//   - verifikasi gagal        -> JANGAN tulis file, log error.
func (a *EdgeClusterAgent) syncSmartDistProfile(profileID, wantHash string) error {
	err := a.syncSmartDistProfileInner(profileID, wantHash)
	if err != nil {
		log.Printf("[smartdist] %v", err)
	}
	return err
}

func (a *EdgeClusterAgent) syncSmartDistProfileInner(profileID, wantHash string) error {
	wantHash = strings.ToLower(strings.TrimSpace(wantHash))

	if strings.TrimSpace(profileID) == "" {
		if err := atomicWriteString(smartDistProfilePath, smartDistDisabledLua, 0o644); err != nil {
			return fmt.Errorf("tulis profil nonaktif gagal: %w", err)
		}
		a.setProfileHash("")
		return nil
	}

	if wantHash == "" {
		return fmt.Errorf("profil %s tanpa hash, ditolak", profileID)
	}

	a.mu.RLock()
	masterURL := a.masterURL
	nodeID := a.state.NodeID
	nodeKey := a.state.NodeKey
	storedHash := a.state.ProfileHash
	a.mu.RUnlock()

	if wantHash == storedHash {
		return nil
	}

	if masterURL == "" || nodeID == "" || nodeKey == "" {
		return fmt.Errorf("node belum terdaftar")
	}

	q := url.Values{}
	q.Set("node_id", nodeID)
	q.Set("node_key", nodeKey)
	resp, err := a.httpClient.Get(masterURL + "/api/cluster/profile?" + q.Encode())
	if err != nil {
		return fmt.Errorf("GET profil gagal: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET profil HTTP %d", resp.StatusCode)
	}

	body, err := io.ReadAll(io.LimitReader(resp.Body, 8<<20))
	if err != nil {
		return fmt.Errorf("baca profil gagal: %w", err)
	}

	sum := sha256.Sum256(body)
	gotHash := hex.EncodeToString(sum[:])
	if gotHash != wantHash {
		return fmt.Errorf("VERIFIKASI GAGAL profil %s: hash body %s != want %s; file TIDAK ditulis", profileID, gotHash, wantHash)
	}

	lua, err := generateSmartDistLua(body)
	if err != nil {
		return err
	}

	if err := atomicWriteString(smartDistProfilePath, lua, 0o644); err != nil {
		return fmt.Errorf("tulis profil gagal: %w", err)
	}

	a.setProfileHash(gotHash)
	log.Printf("[smartdist] profil %s tersinkron (%d byte)", profileID, len(lua))
	return nil
}

func (a *EdgeClusterAgent) setProfileHash(h string) {
	a.mu.Lock()
	a.state.ProfileHash = h
	_ = a.saveState()
	a.mu.Unlock()
}
