package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

// Konversi dokumen profil SmartDist (JSON dari panel) menjadi potongan Lua
// yang dibaca plugin di node. Format keputusan operator 2026-10-09.
//
// ponytail: tipe rule tak dikenal -> error, bukan diabaikan. Fail closed:
// lebih baik file lama dipertahankan daripada menulis profil setengah jadi.

type smartDistProfileDoc struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Smartdist smartDistConfig `json:"smartdist"`
}

type smartDistConfig struct {
	Enabled bool            `json:"enabled"`
	Rules   []smartDistRule `json:"rules"`
}

type smartDistRule struct {
	Type    string   `json:"type"`
	Name    string   `json:"name"`
	File    string   `json:"file"`
	Pattern string   `json:"pattern"`
	Target  string   `json:"target"`
	IPSet   string   `json:"ip_set"`
	Targets []string `json:"targets"`
	Exclude string   `json:"exclude"`
}

func generateSmartDistLua(profile []byte) (string, error) {
	var doc smartDistProfileDoc
	if err := json.Unmarshal(profile, &doc); err != nil {
		return "", fmt.Errorf("smartdist: profil JSON tidak valid: %w", err)
	}

	var b strings.Builder
	b.WriteString("-- SmartDist profile (auto-generated by panel agent, do not edit)\n")
	fmt.Fprintf(&b, "SMARTDIST_ENABLED = %t\n", doc.Smartdist.Enabled)

	for i, r := range doc.Smartdist.Rules {
		switch r.Type {
		case "ip_set":
			fmt.Fprintf(&b, "smartdns_ip_set(%s, %s)\n", luaQuote(r.Name), luaQuote(r.File))
		case "cname":
			fmt.Fprintf(&b, "smartdns_cname(%s, %s)\n", luaQuote(r.Pattern), luaQuote(r.Target))
		case "alias":
			ips := make([]string, 0, len(r.Targets))
			for _, t := range r.Targets {
				ips = append(ips, luaQuote(t))
			}
			if r.Exclude != "" {
				fmt.Fprintf(&b, "smartdns_ip_rules_alias(%s, {%s}, %s)\n",
					luaQuote(r.IPSet), strings.Join(ips, ", "), luaQuote(r.Exclude))
			} else {
				fmt.Fprintf(&b, "smartdns_ip_rules_alias(%s, {%s})\n",
					luaQuote(r.IPSet), strings.Join(ips, ", "))
			}
		default:
			return "", fmt.Errorf("smartdist: tipe rule tidak dikenal %q (rule ke-%d)", r.Type, i)
		}
	}
	return b.String(), nil
}

// luaQuote menghasilkan literal string Lua berkutip ganda dengan escape minimal.
func luaQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		default:
			// Control bytes keep the generated Lua well-formed and keep the value
			// byte-identical round-trip after loadfile. Always three digits (\ddd):
			// Lua reads up to 3, so \1 followed by "2" would otherwise become \12.
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\%03d`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}
